server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:8000/dms_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    show-sql: true
  flyway:
    enabled: true